# standard jekyll configuration options

exclude: ['Rakefile', 'README.md', 'config.rb', 'Gemfile', 'Gemfile.lock']

# configuration required for some pages

domain: foldl.tk
title: 码字
author: Li Zhengji
email: foldl@outlook.com
description: "random hacks, erlang, mathematica, etc"

plugins:     ./_plugins

safe:        false 
future:      false
lsi:         false 
pygments:    true
markdown:    maruku
permalink:   date
excerpt_separator: "\n"

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-45774748-1

# forkme: 

github:
  username: foldl

disqus:
  id: foldl

